export const initialData = [
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'In Progress',
    icon: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'Complete',
    icon: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'Pending',
    icon: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'Approved',
    icon: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'Rejected',
    icon: '/avatars/avatar9.png',
  },
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'In Progress',
    icon: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin page',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'Complete',
    icon: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'Pending',
    icon: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'Approved',
    icon: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'Rejected',
    icon: '/avatars/avatar9.png',
  },
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'In Progress',
    icon: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'Complete',
    icon: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'Pending',
    icon: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'Approved',
    icon: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'Rejected',
    icon: '/avatars/avatar9.png',
  },
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'In Progress',
    icon: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin page',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'Complete',
    icon: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'Pending',
    icon: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'Approved',
    icon: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'Rejected',
    icon: '/avatars/avatar9.png',
  },
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'In Progress',
    icon: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'Complete',
    icon: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'Pending',
    icon: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'Approved',
    icon: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'Rejected',
    icon: '/avatars/avatar9.png',
  },
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'In Progress',
    icon: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin page',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'Complete',
    icon: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'Pending',
    icon: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'Approved',
    icon: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'Rejected',
    icon: '/avatars/avatar9.png',
  },
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'In Progress',
    icon: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'Complete',
    icon: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'Pending',
    icon: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'Approved',
    icon: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'Rejected',
    icon: '/avatars/avatar9.png',
  },
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'In Progress',
    icon: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin page',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'Complete',
    icon: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'Pending',
    icon: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'Approved',
    icon: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'Rejected',
    icon: '/avatars/avatar9.png',
  },
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'In Progress',
    icon: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'Complete',
    icon: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'Pending',
    icon: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'Approved',
    icon: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'Rejected',
    icon: '/avatars/avatar9.png',
  },
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'In Progress',
    icon: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin page',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'Complete',
    icon: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'Pending',
    icon: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'Approved',
    icon: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'Rejected',
    icon: '/avatars/avatar9.png',
  },
]

export const columns = [
  { Header: 'Order ID', accessor: 'id' },
  { Header: 'User', accessor: 'user' },
  { Header: 'Project', accessor: 'project' },
  { Header: 'Address', accessor: 'address' },
  { Header: 'Date', accessor: 'date' },
  { Header: 'Status', accessor: 'status' },
]
