export const initialData = [
  {
    id: '#CM9801',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'IN_PROGRESS',
    avatar: '/avatars/avatar6.png',
  },
  {
    id: '#CM9802',
    user: 'Kate Morrison',
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'COMPLETE',
    avatar: '/avatars/avatar10.png',
  },
  {
    id: '#CM9803',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'PENDING',
    avatar: '/avatars/avatar7.png',
  },
  {
    id: '#CM9804',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'APPROVED',
    avatar: '/avatars/avatar8.png',
  },
  {
    id: '#CM9805',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'REJECTED',
    avatar: '/avatars/avatar9.png',
  },
  {
    id: '#CM9806',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'IN_PROGRESS',
    avatar: '/avatars/avatar6.png',
  },
  {
    id: '#CM9807',
    user: 'Kate Morrison',
    project: 'CRM Admin page',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'COMPLETE',
    avatar: '/avatars/avatar10.png',
  },
  {
    id: '#CM9808',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'PENDING',
    avatar: '/avatars/avatar7.png',
  },
  {
    id: '#CM9809',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'APPROVED',
    avatar: '/avatars/avatar8.png',
  },
  {
    id: '#CM9810',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'REJECTED',
    avatar: '/avatars/avatar9.png',
  },

  {
    id: '#CM9811',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'IN_PROGRESS',
    avatar: '/avatars/avatar6.png',
  },
  {
    id: '#CM9812',
    user: 'Kate Morrison',
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'COMPLETE',
    avatar: '/avatars/avatar10.png',
  },
  {
    id: '#CM9813',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'PENDING',
    avatar: '/avatars/avatar7.png',
  },
  {
    id: '#CM9814',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'APPROVED',
    avatar: '/avatars/avatar8.png',
  },
  {
    id: '#CM9815',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'REJECTED',
    avatar: '/avatars/avatar9.png',
  },
  {
    id: '#CM9816',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'IN_PROGRESS',
    avatar: '/avatars/avatar6.png',
  },
  {
    id: '#CM9817',
    user: 'Kate Morrison',
    project: 'CRM Admin page',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'COMPLETE',
    avatar: '/avatars/avatar10.png',
  },
  {
    id: '#CM9818',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'PENDING',
    avatar: '/avatars/avatar7.png',
  },
  {
    id: '#CM9819',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'APPROVED',
    avatar: '/avatars/avatar8.png',
  },
  {
    id: '#CM9820',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'REJECTED',
    avatar: '/avatars/avatar9.png',
  },
  {
    id: '#CM9821',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'IN_PROGRESS',
    avatar: '/avatars/avatar6.png',
  },
  {
    id: '#CM9822',
    user: 'Kate Morrison',
    project: 'CRM Admin pages',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'COMPLETE',
    avatar: '/avatars/avatar10.png',
  },
  {
    id: '#CM9823',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'PENDING',
    avatar: '/avatars/avatar7.png',
  },
  {
    id: '#CM9824',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'APPROVED',
    avatar: '/avatars/avatar8.png',
  },
  {
    id: '#CM9825',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'REJECTED',
    avatar: '/avatars/avatar9.png',
  },
  {
    id: '#CM9826',
    user: 'Natali Craig',
    project: 'Landing Page',
    address: 'Meadow Lane Oakland',
    date: 'Just now',
    status: 'IN_PROGRESS',
    avatar: '/avatars/avatar6.png',
  },
  {
    id: '#CM9827',
    user: 'Kate Morrison',
    project: 'CRM Admin page',
    address: 'Larry San Francisco',
    date: 'A minute ago',
    status: 'COMPLETE',
    avatar: '/avatars/avatar10.png',
  },
  {
    id: '#CM9828',
    user: 'Drew Cano',
    project: 'Client Project',
    address: 'Bagwell Avenue Ocala',
    date: '1 hour ago',
    status: 'PENDING',
    avatar: '/avatars/avatar7.png',
  },
  {
    id: '#CM9829',
    user: 'Orlando Diggs',
    project: 'Admin Dashboard',
    address: 'Market Street Boston',
    date: 'Yesterday',
    status: 'APPROVED',
    avatar: '/avatars/avatar8.png',
  },
  {
    id: '#CM9830',
    user: 'Andi Lane',
    project: 'App Landing Page',
    address: 'Nest Lane Olivette',
    date: 'Feb 2, 2023',
    status: 'REJECTED',
    avatar: '/avatars/avatar9.png',
  },
]
